### ISSUE TITLE
Missing spell: Supporting Fire

### ISSUE THREAD

**Issue by kedryte** [BloodDragon2580/venture-plan#1]
Thank you for your update/continuation!

Could you please add this spell from the new missions?

![image](https://user-images.githubusercontent.com/69787283/124839402-b910ce80-df56-11eb-8ced-26cbc04cb177.png)

**Comment by BloodDragon2580** [comment]
I will look into this next Days.

**Comment by kedryte** [comment]
Great, thank you!
