### ISSUE TITLE
What's the origin of this repo?

### ISSUE THREAD

**Issue by dphennessy** [BloodDragon2580/venture-plan#4]
Seems like the old repo https://github.com/Gaboros/Venture-Plan-Missions/ got deleted, and with this being a copy of it with some readme changes I'm wondering why this was made, was it in anticipation of the other one being deleted? why did the other one even get deleted?  
Not complaining, I'm glad the changes weren't lost and there's somewhere we can continue to contribute. But I'm wondering what happened.

**Comment by BloodDragon2580** [comment]
I think the real developer of Venture Plan contacted the others and told them to close it. I think it's only a matter of time before this can happen to me too.
